### ISSUE TITLE
是否存在数据量限制

### ISSUE THREAD

**Issue by yi-jy** [zanjs/xlsx2json#1]
excel表格如果行数太多，比如几万行，是不是就会导致解析报错啊？我这边好像遇到这个问题了，有办法解决吗？

**Comment by zanjs** [comment]
@joy-yi0905 您好！ 方便贴一下错误提示吗？

**Comment by yi-jy** [comment]
嗯，几万行没问题的。是我刚弄错了，因为表格里有几个子表，其中有一个字表有一百多万行，然后运行转换时，出现报错了。于是我把那些不用的子表删掉，就转换那几万行，就好了！

之前的截图：

![image](https://cloud.githubusercontent.com/assets/10655307/12029602/d39e952a-ae29-11e5-8799-8868206d5b25.png)
